### ISSUE TITLE
大佬，你好，我把lasertagger-chinese用到了文本纠错

### ISSUE THREAD

**Issue by soft-pure-empty** [425776024/lasertagger-chinese#6]
但是差不多训练几千对句子，loss就降到了0.6的样子，之后就一直震荡。然后用来预测，输入错误句子之后输出的依然是错误句子。
大佬知道是什么问题吗。数据集我检查了是没问题的。

**Comment by 425776024** [comment]
输入错误句子之后输出的依然是错误句子。是什么意思？

**Comment by 425776024** [comment]
> 但是差不多训练几千对句子，loss就降到了0.6的样子，之后就一直震荡。然后用来预测，输入错误句子之后输出的依然是错误句子。
> 大佬知道是什么问题吗。数据集我检查了是没问题的。

输入错误句子之后输出的依然是错误句子。是什么意思？

**Comment by soft-pure-empty** [comment]
我做的纠错是输入错误句子，然后输出修改，再用修改还原出正确句子。我想会不会是修改标记的问题，之前我用英文版的，输出的label_map.txt文件好像和这个版本的版本的不一样。另外我按照示例数据字符与字符之间没留空格，这个应该不会有什么影响吧

**Comment by 425776024** [comment]
> 我做的纠错是输入错误句子，然后输出修改，再用修改还原出正确句子。我想会不会是修改标记的问题，之前我用英文版的，输出的label_map.txt文件好像和这个版本的版本的不一样。另外我按照示例数据字符与字符之间没留空格，这个应该不会有什么影响吧

你用的原来一模一样的参数？max_len这些....，你试着拿训练数据的输入，看能得到正确结果吗？如果不能，那几乎没训练一样

**Comment by soft-pure-empty** [comment]
好的，我咋就没想到了，谢谢大佬。

**Comment by datalee** [comment]
用来做纠错效果怎么样？

**Comment by soft-pure-empty** [comment]
> 用来做纠错效果怎么样？

原版的和这个版本的都没啥效果，没找出什么原因，放弃了
